language: cpp

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq automake libtool lua5.2 liblua5.2-dev liblua5.2-0 libpcap-dev g++ autoconf

install:
- sh bootstrap.sh --enable-tests

script:
- make distcheck

