language: cpp

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq automake libtool lua5.1 liblua5.1-dev liblua5.1 liblua5.1-0-dbg libpcap-dev g++ autoconf gdb libnetfilter-queue-dev libjson0-dev gcc-4.8 g++-4.8 libcurl4-gnutls-dev luarocks
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo luarocks install penlight
    - git clone https://github.com/stevedonovan/LDoc.git
    - sudo make -C LDoc install

before_script:
    - sh bootstrap.sh
    - ./configure --enable-tests --enable-curl #--enable-sniffer
    - ulimit -c

script:
    - make distcheck
    - make check

after_failure:
    - cat tests/test-suite.log
    - COREFILE=$(find . -maxdepth 5 -name "core*" | head -n 1)
    - if [[ -f "$COREFILE" ]]; then sudo  gdb -c "$COREFILE" ./src/tracebox/tracebox -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

